### ISSUE TITLE
USER STORY: Register an account

### ISSUE THREAD

**Issue by ssmerd** [ssmerd/creative-design#1]
As a **customer** I can **register an account** so that **she can update their details, see their orders**.

Acceptance criteria:

A user see the website with a link to register their account

# Tasks

- [x] Create a signup page to store customer details
- [x] Let the logged in user to see their details and order
- [x] Let a user to change its password 
- [x] Test the new functionality
