### ISSUE TITLE
USER STORY: Login and Logout

### ISSUE THREAD

**Issue by ssmerd** [ssmerd/creative-design#2]
As a **customer** I can **log in and log out** so that **she can update their details, see their orders**.

Acceptance criteria:

A user see the website with a link to  log in
A user's information is stored in a database model.
A user can login to the website and order a graphical design

# Tasks

- [x] Create a log in page
- [x] Create a login  outpage
- [x] Let a user to change its password 
- [x] Test the new functionality
