### ISSUE TITLE
USER STORY: Recover my password

### ISSUE THREAD

**Issue by ssmerd** [ssmerd/creative-design#3]
As a **customer** I can **recover a password** so that **she can log in**.

Acceptance criteria:

A user see the website with a link to sign up and or log in
A user can recover their passowrd
A user's information is stored in a database model.

# Tasks

- [x] Create a signup page to store customer details
- [x] Create a login page
- [x] Let the user to recover their password
- [x] Test the new functionality
