### ISSUE TITLE
USER STORY: Have a profile

### ISSUE THREAD

**Issue by ssmerd** [ssmerd/creative-design#4]
As a **customer** I can **have a profile** so that **she can update their details, see their orders**.

Acceptance criteria:

A user see the website with a link to sign up and or log in
A user can sign up and or log/in to the website.
A user's information is stored in a database model.
A user can update their profile information
A user can see their order

# Tasks

- [x] Create a signup page to store customer details
- [x] Let the logged in user to see their details and order
- [x] Test the new functionality
